@startuml

' hide empty description

[*] --> AuthN
[*] --> Basic

state Basic {
    [*] --> CRUD
    CRUD -down-> transaction
    transaction -> reporting
}

Basic -> i18n
Basic -> Realtime

AuthN -> Basic
AuthN -down-> authZ

@enduml