@startuml

state Security {
    AuthN -> AuthZ
}

state Basic {
    [*] --> CRUD
    CRUD -down-> Transaction
    Transaction -down-> Reporting
}

state Live_Data {
    Realtime -> Notification
    Realtime -left-> Streaming
}

Security -left> Basic
Basic -> Security

CRUD -> Migration_Seeding
CRUD -> Pagination
CRUD -> I18n
CRUD -> Worker

Basic -> Realtime

Reporting -> Dashboard : simple data summary
Realtime -> Dashboard : in a short time window

' problem descriptions

CRUD : - Single model modification
CRUD : - CQRS pattern
CRUD : - REST API

Transaction : - Multiple abstract models
Transaction : - Distributed
Transaction : e.g. live gps
Transaction : e.g. buying tickets
Transaction : e.g. checking attendances

Worker : - Background jpb
Worker : - Scheduler / Cron

AuthN : - JWT
AuthN : - OAuth 2

I18n : e.g. Gregorgian vs Buddism calendar

Realtime : e.g. GPS tracking
Realtime : e.g. instant data updates 

Notification : - Notify mobile devices
Notification : - Webpush
' Notification : - 

Dashboard : <i>nice to have</i>
Dashboard : - quick data statistics

@enduml
