@startuml

' hide empty description

state Security {
    AuthN -> AuthZ
}

state Basic {
    [*] --> CRUD
    CRUD -down-> Transaction
    Transaction -down-> Reporting
}

state Live_Data {
    Realtime -> Notification
    Realtime -left-> Streaming
}

Security -left> Basic
Basic -> Security

CRUD -> I18n

Basic -> Realtime

Reporting -> Dashboard
Realtime -> Dashboard

' problem descriptions

Realtime : e.g. GPS tracking
Realtime : e.g. instant data updates

Notification : Mobile devices, Webpush

Dashboard : quick data statistics
Dashboard : <i>nice to have</i>

@enduml