version: '3.3'

services:

  mongo:
    image: mongo:3
    container_name: mongo
    # restart: always
    networks: 
    - graylog-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.1
    container_name: elasticsearch
    # restart: always
    environment:
      http.host: 0.0.0.0
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      
    networks: 
    - graylog-net
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g

  graylog:
    image: graylog/graylog:3.0
    container_name: graylog
    links: 
    - mongo
    - elasticsearch
    ports: 
    - 9000:9000
    - 12201:12201
    - 1514:1514
    environment: 
      GRAYLOG_HTTP_EXTERNAL_URI: http://127.0.0.1:9000/
    networks: 
    - graylog-net

networks: 
  graylog-net: